In [20]:
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score

In [21]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [22]:
dataset=pd.get_dummies(dataset,drop_first=True)
print(dataset.columns)
dataset

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [23]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [24]:
dependent=dataset[["charges"]]

In [25]:
X_train,X_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.25,random_state=10)

### AdaBoost Algorithm

In [26]:
from sklearn.ensemble import AdaBoostRegressor      # For AdaBoost regression

In [27]:
regressor=AdaBoostRegressor(random_state=10, n_estimators=100)
regressor=regressor.fit(X_train,y_train)

c:\ProgramData\anaconda3\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [28]:
y_pred=regressor.predict(X_test)
r_score=r2_score(y_test,y_pred)
r_score

0.8215713249770599

### XGBoost Algorithm

In [29]:
# !pip install xgboost
from xgboost import XGBRegressor                 # For XGBoost regression

In [30]:
regressor=XGBRegressor(random_state=10, n_estimators=100, learning_rate=0.1, max_depth=3)
regressor=regressor.fit(X_train,y_train)

In [31]:
y_pred=regressor.predict(X_test)
r_score=r2_score(y_test,y_pred)
r_score

0.8508705828167392

### LightGBM Algorithm

In [32]:
# pip install lightgbm
from lightgbm import LGBMRegressor                 # For LightGBM regression

In [33]:

regressor=LGBMRegressor(random_state=10, n_estimators=100, learning_rate=0.1, max_depth=3)
regressor=regressor.fit(X_train,y_train)

In [34]:
y_pred=regressor.predict(X_test)
r_score=r2_score(y_test,y_pred)
r_score

0.8530383966060129