In [ ]:
import yfinance as yf
import pandas as pd

In [ ]:
nifty50_tickers = [
    "HDFCBANK.NS",                  # HDFC Bank
    "ICICIBANK.NS",                 # ICICI Bank
    "RELIANCE.NS",                  # Reliance Industries
    "AXISBANK.NS",                  # Axis Bank
    "BAJFINANCE.NS",                # Bajaj Finance
    "ADANIPORTS.NS",                # Adani Ports & SEZ
    "SBIN.NS",                      # State Bank of India
    "SUNPHARMA.NS",                 # Sun Pharmaceutical Industries
    "BHARTIARTL.NS",                # Bharti Airtel
    "ITC.NS",                       # ITC Limited
    "KOTAKBANK.NS",                 # Kotak Mahindra Bank
    "TATAMOTORS.NS",                # Tata Motors
    "INFY.NS",                      # Infosys
    "TCS.NS",                       # Tata Consultancy Services
    "HCLTECH.NS",                   # HCLTech
    "BEL.NS",                       # Bharat Electronics
    "ONGC.NS",                      # Oil and Natural Gas Corporation
    "NTPC.NS",                      # NTPC Limited
    "EICHERMOT.NS",                 # Eicher Motors
    "LT.NS",                        # Larsen & Toubro
    "COALINDIA.NS",                 # Coal India
    "CIPLA.NS",                     # Cipla
    "GRASIM.NS",                    # Grasim Industries
    "ULTRACEMCO.NS",                # UltraTech Cement
    "TITAN.NS",                     # Titan Company
    "JSWSTEEL.NS",                  # JSW Steel
    "ETERNAL.NS",                   # Eternal Limited
    "POWERGRID.NS",                 # Power Grid Corporation of India
    "TRENT.NS",                     # Trent Limited
    "ADANIENT.NS",                  # Adani Enterprises
    "WIPRO.NS",                     # Wipro
    "MARUTI.NS",                    # Maruti Suzuki
    "HINDALCO.NS",                  # Hindalco Industries
    "HINDUNILVR.NS",                # Hindustan Unilever
    "SBILIFE.NS",                   # “SBI Life Insurance” 
    "TATASTEEL.NS",                 # Tata Steel Ltd
    "HDFCLIFE.NS",                  # “HDFC Life Insurance”
    "DRREDDY.NS",                   # Dr. Reddy’s Laboratories
    "JIOFINANCIAL.NS",              # Jio Financial Services
    "BAJAJFINSV.NS",                # Bajaj Finserv
    "BAJAJ-AUTO.NS",                # Bajaj Auto (or "BAJAJAUTO.NS")
    "ASIANPAINT.NS",                # Asian Paints
    "TATACONSUM.NS",                # Tata Consumer Products
    "TECHM.NS",                     # Tech Mahindra
    "APOLLOHOSP.NS",                # Apollo Hospitals
    "M&M.NS",                       # Mahindra & Mahindra
    "MAXHEALTH.NS",                 # Max Healthcare
    "INDIGO.NS",                    # IndiGo (InterGlobe Aviation)
    "NESTLEIND.NS",                 # Nestlé India
    "SHRIRAMFIN.NS"                 # Shriram Finance Ltd
]


index_tickers = {
    "NIFTY50": "^NSEI",
}

In [ ]:

start_date = "2014-01-01"
end_date   = "2024-12-31"

all_data = []

for ticker in nifty50_tickers:

    print(f"Downloading {ticker} ...")
    df = yf.download(ticker, start=start_date, end=end_date, multi_level_index=False, auto_adjust=True)


    info_ticker = yf.Ticker(ticker)
    
    if not df.empty:
        df["Stock"] = ticker.replace(".NS", "")
        df['Sector'] = info_ticker.info['sector']
        df['Industry'] = info_ticker.info['industry']
        df['Market Cap'] = info_ticker.info['marketCap']

        df.reset_index(inplace=True)   # Move Date from index to column
        all_data.append(df)


# Combine all stock data
stocks_df = pd.concat(all_data, ignore_index=True)

stocks_df.to_csv("nifty50_stocks.csv", index=False)
stocks_df

Downloading HDFCBANK.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading ICICIBANK.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading RELIANCE.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading AXISBANK.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading BAJFINANCE.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading ADANIPORTS.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading SBIN.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading SUNPHARMA.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading BHARTIARTL.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading ITC.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading KOTAKBANK.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading TATAMOTORS.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading INFY.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading TCS.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading HCLTECH.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading BEL.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading ONGC.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading NTPC.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading EICHERMOT.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading LT.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading COALINDIA.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading CIPLA.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading GRASIM.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading ULTRACEMCO.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading TITAN.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading JSWSTEEL.NS ...

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Downloading ETERNAL.NS ...

Downloading POWERGRID.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading TRENT.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading ADANIENT.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading WIPRO.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading MARUTI.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading HINDALCO.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading HINDUNILVR.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading SBILIFE.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading TATASTEEL.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading HDFCLIFE.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading DRREDDY.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading JIOFINANCIAL.NS ...

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: JIOFINANCIAL.NS"}}}
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['JIOFINANCIAL.NS']: YFTzMissingError('possibly delisted; no timezone found')

Downloading BAJAJFINSV.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading BAJAJ-AUTO.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading ASIANPAINT.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading TATACONSUM.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading TECHM.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading APOLLOHOSP.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading M&M.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading MAXHEALTH.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading INDIGO.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading NESTLEIND.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading SHRIRAMFIN.NS ...

[*********************100%***********************]  1 of 1 completed

,Date,Close,High,Low,Open,Volume,Stock,Sector,Industry,Market Cap
0,2014-01-01,145.392685,146.409103,144.922719,146.015651,4492436,HDFCBANK,Financial Services,Banks - Regional,14818861907968
1,2014-01-02,143.611237,147.491144,142.857111,145.359927,7228992,HDFCBANK,Financial Services,Banks - Regional,14818861907968
2,2014-01-03,144.944565,145.578470,142.081090,142.518262,6513184,HDFCBANK,Financial Services,Banks - Regional,14818861907968
3,2014-01-06,144.638565,144.922725,143.611207,144.922725,5963420,HDFCBANK,Financial Services,Banks - Regional,14818861907968
4,2014-01-07,145.228760,146.660498,142.802444,145.818932,7896920,HDFCBANK,Financial Services,Banks - Regional,14818861907968
...,...,...,...,...,...,...,...,...,...,...
126939,2024-12-23,571.339233,585.429953,569.337575,575.917235,4691250,SHRIRAMFIN,Financial Services,Credit Services,1214284562432
126940,2024-12-24,571.349121,574.252482,565.829742,571.358979,2020780,SHRIRAMFIN,Financial Services,Credit Services,1214284562432
126941,2024-12-26,580.059204,581.852750,569.010528,573.202120,4462340,SHRIRAMFIN,Financial Services,Credit Services,1214284562432
126942,2024-12-27,574.510193,582.625693,572.845410,582.041089,1524915,SHRIRAMFIN,Financial Services,Credit Services,1214284562432
126943,2024-12-30,578.493530,588.372939,573.796624,577.264811,3452720,SHRIRAMFIN,Financial Services,Credit Services,1214284562432

In [ ]:
nifty_df = yf.download('^NSEI', start=start_date, end=end_date, multi_level_index=False, auto_adjust=True)
nifty_df.reset_index(inplace=True)

nifty_df.to_csv('NIFTY50.csv')
 
nifty_df

[*********************100%***********************]  1 of 1 completed

,Date,Close,High,Low,Open,Volume
0,2014-01-02,6221.149902,6358.299805,6211.299805,6301.250000,158100
1,2014-01-03,6211.149902,6221.700195,6171.250000,6194.549805,139000
2,2014-01-06,6191.450195,6224.700195,6170.250000,6220.850098,118300
3,2014-01-07,6162.250000,6221.500000,6144.750000,6203.899902,138600
4,2014-01-08,6174.600098,6192.100098,6160.350098,6178.049805,146900
...,...,...,...,...,...,...
2693,2024-12-23,23753.449219,23869.550781,23647.199219,23738.199219,189800
2694,2024-12-24,23727.650391,23867.650391,23685.150391,23769.099609,177700
2695,2024-12-26,23750.199219,23854.500000,23653.599609,23775.800781,177700
2696,2024-12-27,23813.400391,23938.849609,23800.599609,23801.400391,176800
2697,2024-12-30,23644.900391,23915.349609,23599.300781,23796.900391,364900