In [1]:
import yfinance as yf
import pandas as pd

In [3]:
nifty50_tickers = [
    "ADANIENT.NS",
    "ADANIPORTS.NS",
    "APOLLOHOSP.NS",
    "ASIANPAINT.NS",
    "AXISBANK.NS",
    "BAJAJ-AUTO.NS",
    "BAJFINANCE.NS",
    "BAJAJFINSV.NS",
    "BEL.NS",
    "BHARTIARTL.NS",
    "CIPLA.NS",
    "COALINDIA.NS",
    "DRREDDY.NS",
    "EICHERMOT.NS",
    "GRASIM.NS",
    "HCLTECH.NS",
    "HDFCBANK.NS",
    "HDFCLIFE.NS",
    "HINDALCO.NS",
    "HINDUNILVR.NS",
    "ICICIBANK.NS",
    "INFY.NS",
    "ITC.NS",
    "JIOFIN.NS",
    "JSWSTEEL.NS",
    "KOTAKBANK.NS",
    "LT.NS",
    "M&M.NS",
    "MARUTI.NS",
    "NESTLEIND.NS",
    "NTPC.NS",
    "ONGC.NS",
    "POWERGRID.NS",
    "RELIANCE.NS",
    "SBILIFE.NS",
    "SHRIRAMFIN.NS",
    "SBIN.NS",
    "SUNPHARMA.NS",
    "TCS.NS",
    "TATACONSUM.NS",
    "TATAMOTORS.NS",
    "TATASTEEL.NS",
    "TECHM.NS",
    "TITAN.NS",
    "TRENT.NS",
    "ULTRACEMCO.NS",
    "WIPRO.NS"
]




index_tickers = {
    "NIFTY50": "^NSEI",
}

In [4]:

start_date = "2014-01-01"
end_date   = "2024-12-31"

all_data = []

for ticker in nifty50_tickers:

    print(f"Downloading {ticker} ...")
    df = yf.download(ticker, start=start_date, end=end_date, multi_level_index=False, auto_adjust=True)


    info_ticker = yf.Ticker(ticker)
    
    if not df.empty:
        df["Stock"] = ticker.replace(".NS", "")
        df['Sector'] = info_ticker.info['sector']
        df['Industry'] = info_ticker.info['industry']
        df['Market Cap'] = info_ticker.info['marketCap']

        df.reset_index(inplace=True)   # Move Date from index to column
        all_data.append(df)


# Combine all stock data
stocks_df = pd.concat(all_data, ignore_index=True)

stocks_df.to_csv("nifty50_stocks.csv", index=False)
stocks_df

Downloading ADANIENT.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading ADANIPORTS.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading APOLLOHOSP.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading ASIANPAINT.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading AXISBANK.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading BAJAJ-AUTO.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading BAJFINANCE.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading BAJAJFINSV.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading BEL.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading BHARTIARTL.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading CIPLA.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading COALINDIA.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading DRREDDY.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading EICHERMOT.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading GRASIM.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading HCLTECH.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading HDFCBANK.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading HDFCLIFE.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading HINDALCO.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading HINDUNILVR.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading ICICIBANK.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading INFY.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading ITC.NS ...

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Downloading JIOFIN.NS ...

Downloading JSWSTEEL.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading KOTAKBANK.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading LT.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading M&M.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading MARUTI.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading NESTLEIND.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading NTPC.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading ONGC.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading POWERGRID.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading RELIANCE.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading SBILIFE.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading SHRIRAMFIN.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading SBIN.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading SUNPHARMA.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading TCS.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading TATACONSUM.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading TATAMOTORS.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading TATASTEEL.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading TECHM.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading TITAN.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading TRENT.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading ULTRACEMCO.NS ...

[*********************100%***********************]  1 of 1 completed

Downloading WIPRO.NS ...

[*********************100%***********************]  1 of 1 completed

,Date,Close,High,Low,Open,Volume,Stock,Sector,Industry,Market Cap
0,2014-01-01,37.932781,38.095098,37.022394,37.234111,7564701,ADANIENT,Energy,Thermal Coal,2994291081216
1,2014-01-02,36.041435,37.932782,35.752089,37.262341,17188171,ADANIENT,Energy,Thermal Coal,2994291081216
2,2014-01-03,35.053421,36.140239,34.510010,35.709744,11525782,ADANIENT,Energy,Thermal Coal,2994291081216
3,2014-01-06,35.575649,35.977915,34.538232,34.989899,10660990,ADANIENT,Energy,Thermal Coal,2994291081216
4,2014-01-07,34.150085,35.977917,34.015998,35.759142,11002957,ADANIENT,Energy,Thermal Coal,2994291081216
...,...,...,...,...,...,...,...,...,...,...
123109,2024-12-23,296.077271,298.721676,293.288630,294.827200,6693583,WIPRO,Technology,Information Technology Services,2532097654784
123110,2024-12-24,293.577087,297.327359,291.173082,295.692624,8837902,WIPRO,Technology,Information Technology Services,2532097654784
123111,2024-12-26,293.336670,295.163737,292.327000,293.673236,6516148,WIPRO,Technology,Information Technology Services,2532097654784
123112,2024-12-27,297.231201,298.962073,293.000158,293.480959,8063921,WIPRO,Technology,Information Technology Services,2532097654784
123113,2024-12-30,292.038544,297.519658,291.028844,297.231189,13709891,WIPRO,Technology,Information Technology Services,2532097654784

In [ ]:
nifty_df = yf.download('^NSEI', start=start_date, end=end_date, multi_level_index=False, auto_adjust=True)
nifty_df.reset_index(inplace=True)

nifty_df.to_csv('NIFTY50.csv')
 
nifty_df

[*********************100%***********************]  1 of 1 completed

,Date,Close,High,Low,Open,Volume
0,2014-01-02,6221.149902,6358.299805,6211.299805,6301.250000,158100
1,2014-01-03,6211.149902,6221.700195,6171.250000,6194.549805,139000
2,2014-01-06,6191.450195,6224.700195,6170.250000,6220.850098,118300
3,2014-01-07,6162.250000,6221.500000,6144.750000,6203.899902,138600
4,2014-01-08,6174.600098,6192.100098,6160.350098,6178.049805,146900
...,...,...,...,...,...,...
2693,2024-12-23,23753.449219,23869.550781,23647.199219,23738.199219,189800
2694,2024-12-24,23727.650391,23867.650391,23685.150391,23769.099609,177700
2695,2024-12-26,23750.199219,23854.500000,23653.599609,23775.800781,177700
2696,2024-12-27,23813.400391,23938.849609,23800.599609,23801.400391,176800
2697,2024-12-30,23644.900391,23915.349609,23599.300781,23796.900391,364900