In [9]:
# importing libraries
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

#Read the movie Dataset
i_cols = ['movie_id', 'movie_title' ,'release_date','video_release date', 'IMDb_URL', 'unknown', 'Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
movies = pd.read_csv('ml-100k/u.item', sep='|', names=i_cols,encoding='latin-1')

# reading ratings file:
r_cols = ['user_id', 'movie_id', 'rating', 'unix_timestamp']
ratings = pd.read_csv('ml-100k/u.data', sep='\t', names=r_cols,encoding='latin-1')

# Specify genre columns
genre_columns =['Action', 'Adventure', 'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
movies.head(3)

,movie_id,movie_title,release_date,video_release date,IMDb_URL,unknown,Action,Adventure,Animation,Children's,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [ ]:
# We give 1 for every rating from user - no of times any movie is watched and rated makes it popular.
ratings['popularity']=1
ratings.drop(columns=['rating', 'user_id', 'unix_timestamp'], axis=1, inplace=True)
popularity_df = ratings.groupby('movie_id').sum().reset_index()
popularity_df.set_index('movie_id', inplace=True)
mov_ind = movies.set_index('movie_id')

popularity_df

          popularity
movie_id
1                452
2                131
3                 90
4                209
5                 86
...              ...
1678               1
1679               1
1680               1
1681               1
1682               1

[1682 rows x 1 columns]

In [19]:
pop_mov_df = popularity_df.join(mov_ind, on='movie_id', how='inner')
pop_sorted = pop_mov_df.sort_values(by='popularity', ascending=False)
pop_sorted

,popularity,movie_title,release_date,video_release date,IMDb_URL,unknown,Action,Adventure,Animation,Children's,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
movie_id,,,,,,,,,,,,,,,,,,,,,
50,583,Star Wars (1977),01-Jan-1977,NaN,http://us.imdb.com/M/title-exact?Star%20Wars%2...,0,1,1,0,0,...,0,0,0,0,0,1,1,0,1,0
258,509,Contact (1997),11-Jul-1997,NaN,http://us.imdb.com/Title?Contact+(1997/I),0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100,508,Fargo (1996),14-Feb-1997,NaN,http://us.imdb.com/M/title-exact?Fargo%20(1996),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
181,507,Return of the Jedi (1983),14-Mar-1997,NaN,http://us.imdb.com/M/title-exact?Return%20of%2...,0,1,1,0,0,...,0,0,0,0,0,1,1,0,1,0
294,485,Liar Liar (1997),21-Mar-1997,NaN,http://us.imdb.com/Title?Liar+Liar+(1997),0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1626,1,Nobody Loves Me (Keiner liebt mich) (1994),09-Feb-1996,NaN,http://us.imdb.com/M/title-exact?Keiner%20lieb...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1630,1,"Silence of the Palace, The (Saimt el Qusur) (1...",02-Feb-1996,NaN,http://us.imdb.com/M/title-exact?Saimt%20el%20...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1632,1,Land and Freedom (Tierra y libertad) (1995),29-Mar-1996,NaN,http://us.imdb.com/M/title-exact?Tierra%20y%20...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1681,1,You So Crazy (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?You%20So%20Cr...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1682,1,Scream of Stone (Schrei aus Stein) (1991),08-Mar-1996,NaN,http://us.imdb.com/M/title-exact?Schrei%20aus%...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [20]:

for genre in genre_columns:
    print(f'\nThe Top 5 Popular movies in {genre} genre :\n')
    top5_genre = pop_sorted[pop_sorted[genre]>0].head(5)['movie_title'].values
    for top5 in top5_genre:
        print(top5)

The Top 5 Popular movies in Action genre :

Star Wars (1977)
Return of the Jedi (1983)
Air Force One (1997)
Independence Day (ID4) (1996)
Raiders of the Lost Ark (1981)

The Top 5 Popular movies in Adventure genre :

Star Wars (1977)
Return of the Jedi (1983)
Raiders of the Lost Ark (1981)
Rock, The (1996)
Empire Strikes Back, The (1980)

The Top 5 Popular movies in Animation genre :

Toy Story (1995)
Lion King, The (1994)
Aladdin (1992)
Beauty and the Beast (1991)
Fantasia (1940)

The Top 5 Popular movies in Children's genre :

Toy Story (1995)
Willy Wonka and the Chocolate Factory (1971)
E.T. the Extra-Terrestrial (1982)
Wizard of Oz, The (1939)
Lion King, The (1994)

The Top 5 Popular movies in Comedy genre :

Liar Liar (1997)
Toy Story (1995)
Back to the Future (1985)
Willy Wonka and the Chocolate Factory (1971)
Princess Bride, The (1987)

The Top 5 Popular movies in Crime genre :

Fargo (1996)
Godfather, The (1972)
Pulp Fiction (1994)
L.A. Confidential (1997)
Usual Suspects, The (1995)

The Top 5 Popular movies in Documentary genre :

Hoop Dreams (1994)
Crumb (1994)
Celluloid Closet, The (1995)
Looking for Richard (1996)
Koyaanisqatsi (1983)

The Top 5 Popular movies in Drama genre :

Contact (1997)
Fargo (1996)
English Patient, The (1996)
Godfather, The (1972)
Pulp Fiction (1994)

The Top 5 Popular movies in Fantasy genre :

E.T. the Extra-Terrestrial (1982)
Nutty Professor, The (1996)
Dragonheart (1996)
Mask, The (1994)
Jumanji (1995)

The Top 5 Popular movies in Film-Noir genre :

L.A. Confidential (1997)
Blade Runner (1982)
Chinatown (1974)
Maltese Falcon, The (1941)
Manchurian Candidate, The (1962)

The Top 5 Popular movies in Horror genre :

Scream (1996)
Alien (1979)
Jaws (1975)
Psycho (1960)
Shining, The (1980)

The Top 5 Popular movies in Musical genre :

Evita (1996)
Blues Brothers, The (1980)
Wizard of Oz, The (1939)
Sound of Music, The (1965)
Lion King, The (1994)

The Top 5 Popular movies in Mystery genre :

Mission: Impossible (1996)
L.A. Confidential (1997)
Conspiracy Theory (1997)
Amadeus (1984)
2001: A Space Odyssey (1968)

The Top 5 Popular movies in Romance genre :

Star Wars (1977)
Return of the Jedi (1983)
English Patient, The (1996)
Jerry Maguire (1996)
Empire Strikes Back, The (1980)

The Top 5 Popular movies in Sci-Fi genre :

Star Wars (1977)
Contact (1997)
Return of the Jedi (1983)
Independence Day (ID4) (1996)
Twelve Monkeys (1995)

The Top 5 Popular movies in Thriller genre :

Fargo (1996)
Scream (1996)
Air Force One (1997)
Silence of the Lambs, The (1991)
Rock, The (1996)

The Top 5 Popular movies in War genre :

Star Wars (1977)
Return of the Jedi (1983)
English Patient, The (1996)
Independence Day (ID4) (1996)
Empire Strikes Back, The (1980)

The Top 5 Popular movies in Western genre :

Dances with Wolves (1990)
Butch Cassidy and the Sundance Kid (1969)
Unforgiven (1992)
Good, The Bad and The Ugly, The (1966)
Maverick (1994)